# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/8bit-adder',
                'doc_host': 'https://mone27.github.io',
                'git_url': 'https://github.com/mone27/8bit-adder',
                'lib_path': '8bit_adder'},
  'syms': {'8bit_adder.core': {'8bit_adder.core.foo': ('core.html#foo', '8bit_adder/core.py')}}}
