# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/8bit-adder',
                'doc_host': 'https://mone27.github.io',
                'git_url': 'https://github.com/mone27/8bit-adder',
                'lib_path': '8bit_adder'},
  'syms': { '8bit_adder.rpi_server': { '8bit_adder.rpi_server.api_set_a': ('core.html#api_set_a', '8bit_adder/rpi_server.py'),
                                       '8bit_adder.rpi_server.api_set_b': ('core.html#api_set_b', '8bit_adder/rpi_server.py'),
                                       '8bit_adder.rpi_server.dec_to_bin_digits': ( 'core.html#dec_to_bin_digits',
                                                                                    '8bit_adder/rpi_server.py'),
                                       '8bit_adder.rpi_server.get_res': ('core.html#get_res', '8bit_adder/rpi_server.py'),
                                       '8bit_adder.rpi_server.set_number': ('core.html#set_number', '8bit_adder/rpi_server.py')}}}
