"""API server running on the raspberry to control the adder inputs"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['pins_a', 'pins_b', 'pins_res', 'app', 'rt', 'pin_sub', 'dec_to_bin_digits', 'set_number', 'get', 'post']

# %% ../nbs/00_core.ipynb #b23521be-7d9e-406b-8b41-f85f910f4810
from fastcore.test import *
from functools import partial

# %% ../nbs/00_core.ipynb #53f09fd0
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BOARD) # numbers from 0 to 40

# %% ../nbs/00_core.ipynb #84ddf06a
pins_a = {
    0: 7,
    1: 11,
    2: 13,
    3: 15}

# %% ../nbs/00_core.ipynb #87af68e7-350e-40b7-a978-63c90d17eb32
pins_b = {
    0: 19,
    1: 21,
    2: 23,
    3: 29}

# %% ../nbs/00_core.ipynb #2d4887e4-0e8c-4581-a735-a5df00f587ae
pins_res = {
    0: 32,
    1: 37,
    2: 35,
    3: 33
}

# %% ../nbs/00_core.ipynb #6270dc97-26a8-48b9-9af7-d50cb6ab484b
GPIO.setup(list(pins_a.values()), GPIO.OUT)
GPIO.setup(list(pins_b.values()), GPIO.OUT)
GPIO.setup(list(pins_res.values()), GPIO.IN)

# %% ../nbs/00_core.ipynb #6498b4e1-2d2a-4c50-ad94-36e474752c38
def dec_to_bin_digits(x):
    """converts decimal to list of 4 binary digits"""
    string = '{0:04b}'.format(x)
    return list(map(int, string))

# %% ../nbs/00_core.ipynb #2dc51ddb-97da-40a1-85d6-01c00ab00670
def set_number(n, pin_map):
    bin_digits = dec_to_bin_digits(n)
    bin_digits.reverse() # need from low bit to high bit
    for i, digit in enumerate(bin_digits):
        GPIO.output(pin_map[i], digit)

# %% ../nbs/00_core.ipynb #bc6fa9ba
from fasthtml.common import *

app, rt = fast_app()

@rt('/')
def get():
    return Titled("4-bit Adder",
        Form(
            Label("A", Input(type='number', name='a', min=0, max=15, value=0)),
            Label("B", Input(type='number', name='b', min=0, max=15, value=0)),
            Button("Add"), hx_post='/add', hx_target='#res',),
        Div(id='res'))

@rt('/add')
def post(a:int, b:int):
    set_number(a, pins_a)
    set_number(b, pins_b)
    return P(f"{a} + {b} = {read_number(pins_res)}")

# %% ../nbs/00_core.ipynb #8ff88f29
@rt('/api/set_a/{num}')
def get(num:int): set_number(num, pins_a); return True

@rt('/api/set_b/{num}')
def get(num:int): set_number(num, pins_b); return True

@rt('/api/get_res')
def get(): return read_number(pins_res)

# %% ../nbs/00_core.ipynb #15f9db17-fac7-417f-9eae-4249c864d72f
serve()

# %% ../nbs/00_core.ipynb #035babd6
pins_a = {
    8: 7,
    7: 11,
    6: 13,
    5: 15,
    4: 19,
    3: 21,
    2: 23,
    1: 29}

# %% ../nbs/00_core.ipynb #91d085b8-1389-46e3-b0d7-fb9f713bbce5
pins_b = {
    8: 32,
    7: 37,
    6: 35,
    5: 33,
    4: 31,
    3: 36,
    2: 38,
    1: 40}

# %% ../nbs/00_core.ipynb #ba89543d-ca5e-45b2-bab9-86a60ecb13d9
pin_sub = 26

# %% ../nbs/00_core.ipynb #b19bb3bc
GPIO.setup(list(pins_a.values()), GPIO.OUT)
GPIO.setup(list(pins_b.values()), GPIO.OUT)
GPIO.setup(pin_sub, GPIO.OUT)
