# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_simulator.ipynb.

# %% auto #0
__all__ = ['Gate', 'And', 'Input', 'Or', 'Xor', 'FullAdder', 'dec_to_bin', 'NBitAdder']

# %% ../nbs/01_simulator.ipynb #73c57a15
class Gate:
    def __init__(self, a, b):
        self.a = a; self.b = b
    def __call__(self) -> bool:
        raise NotImplementedError

# %% ../nbs/01_simulator.ipynb #292de554
class And(Gate):
    def __call__(self) -> bool:
        return self.a() and self.b()

# %% ../nbs/01_simulator.ipynb #20d86523
class Input:
    def __init__(self, value: bool):
        self.value = value
    def __call__(self) -> bool:
        return self.value
    def __repr__(self):
        return str(self.value)

# %% ../nbs/01_simulator.ipynb #221f3651
class Or(Gate):
    def __call__(self) -> bool:
        return self.a() or self.b()

class Xor(Gate):
    def __call__(self) -> bool:
        return self.a() ^ self.b()


# %% ../nbs/01_simulator.ipynb #966f4c63
class FullAdder:
    def __init__(self, a, b, c_in):
        self.a = a
        self.b = b
        self.c_in = c_in
        self.xor1 = Xor(self.a,self.b)
        self.sum = Xor(self.xor1, self.c_in)
        self.and1 = And(self.a,self.b)
        self.and2 = And(self.xor1, self.c_in)
        self.c_out = Or(self.and1, self.and2)


# %% ../nbs/01_simulator.ipynb #662f0e9f
from fastcore.all import patch, compose, L
from math import ceil, floor

# %% ../nbs/01_simulator.ipynb #5840f20d
@patch
def show(self:FullAdder):
    gates = [
        ("XOR1", self.a, self.b, self.xor1),
        ("AND1", self.a, self.b, self.and1),
        ("XOR2", self.xor1, self.c_in, self.sum),
        ("AND2", self.xor1, self.c_in, self.and2),
        ("OR", self.and1, self.and2, self.c_out),
    ]

    for _, a,b, out in gates:
        print(f"{a()}  {b()}  {out()}", end="\t")
    print()
    for i in range(len(gates)):
        print(" |   |   |", end="\t")
    print()

    for name, *_ in gates:
        print(f"    {name}    ", end="\t")
    print()


# %% ../nbs/01_simulator.ipynb #7cda66d0
@patch
def show(self:FullAdder):
    gates = [
        ("XOR1", self.a, self.b, self.xor1),
        ("XOR2", self.xor1, self.c_in, self.sum),
        ("AND1", self.a, self.b, self.and1),
        ("AND2", self.xor1, self.c_in, self.and2),
        ("OR", self.and1, self.and2, self.c_out),
    ]

    sep = " "*5
    for _, a, b, out in gates:
        print(f"{str(a()):>5}  {str(b()):>5}  {str(out()):>5}", end=sep)
    print()
    for i in range(len(gates)):
        print("  |      |      |  ", end=sep)
    print()
    len_spaces = 5*3+2*2 - 4 # 5 is the width of False, 2 times 2 space, 4 is the width of the gate name
    space_before = " " * ceil(len_spaces/2)
    space_after = " " * floor(len_spaces/2)
    for name, *_ in gates:
        print(f"{space_before}{name:^4}{space_after}", end=sep)
    print()


# %% ../nbs/01_simulator.ipynb #ced118a0
def dec_to_bin(x):
    """converts decimal to list of 8 bool, from low significance bit"""
    string = '{0:08b}'.format(x)
    return L(*string).map(int).map(bool)[::-1] # first convert string to int, as any non empty string is try

# %% ../nbs/01_simulator.ipynb #6a74a89d
class NBitAdder:
    def __init__(self, n_bits: int):
        self.n_bits = n_bits
        self.max_value = 2 ** n_bits
        self.a_bits = [Input(False) for _ in range(n_bits)]
        self.b_bits = [Input(False) for _ in range(n_bits)]
        self.adders = [FullAdder(self.a_bits[0], self.b_bits[0], Input(False))] # first carry is always 0
        for i in range(1, n_bits):
            next_adder = FullAdder(self.a_bits[i], self.b_bits[i], self.adders[i-1].c_out)
            self.adders.append(next_adder)
        self.sum_bits = [adder.sum for adder in self.adders]
    
    def check_input(self, n):
        if not 0 <= n < self.max_value:
            raise ValueError(f"Input too big. A {self.n_bits} n bit adder supports numbers up to {self.max_value}, got {n}")

    def set_inputs(self, a: int, b:int):
        self.check_input(a); self.check_input(b)
        a_bool = dec_to_bin(a)[:self.n_bits]
        b_bool = dec_to_bin(b)[:self.n_bits]
        for i, (a_bit, b_bit) in enumerate(zip(a_bool, b_bool)):
            self.a_bits[i].value = a_bit
            self.b_bits[i].value = b_bit
    
    def sum(self):
        return [sum() for sum in self.sum_bits]
    
    def sum_dec(self):
        bits =  [str(int(x)) for x in self.sum()][::-1] # converts bits to 0/1 chars and the reverse the order
        return int("".join(bits), 2)

# %% ../nbs/01_simulator.ipynb #4e0fd12a
@patch
def show(self:NBitAdder):
    print(f"Result: {self.sum_dec()} {self.sum()}")
    for i, adder in enumerate(self.adders):
        print(f"Bit {i}:")
        adder.show()
        print()


# %% ../nbs/01_simulator.ipynb #182692d9
set_b(3)
set_a(12)
